### ISSUE TITLE
Add a Discord/Community Code of Conduct.

### ISSUE THREAD

**Issue by joshualambert** [tidev/organization-docs#1]
We want to add something like this which you'll need to approve before joining the TiDev Discord:
https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md

**Comment by cb1kenobi** [comment]
Another good example is the MariaDB Foundation: https://mariadb.org/about. They have the usual code of conduct and such, but they also cover security policies, analytics usage, by-laws, logos, etc.

**Comment by joshualambert** [comment]
The website itself is ugly AF .... But I can't argue with you, the content is fantastic. There's a lot to learn there. @cb1kenobi

**Comment by joshualambert** [comment]
Here's another possible example for this: https://berlincodeofconduct.org/

**Comment by joshualambert** [comment]
We're going to pull the Berlin Code of Conduct into Github (here) in an MD file and use that as a start point to solve this problem.

**Comment by cb1kenobi** [comment]
Since we're sticking with Slack, we no longer need Discord.
