### ISSUE TITLE
Figure out "Sponsor this Project" side nav section for every GitHub repo

### ISSUE THREAD

**Issue by cb1kenobi** [tidev/organization-docs#15]
We want to list in the side bar all the ways people can donate. I don't see it in the project settings. Probably a GitHub Sponsors thing.

I see someone started signing up for GitHub sponsors, but never finished. https://github.com/sponsors/tidev/dashboard

Liberapay link: https://en.liberapay.com/tidev/

We should also sign up for open collective also: https://opencollective.com/

**Comment by caspahouzer** [comment]
I made some changes https://github.com/sponsors/tidev?preview=true
