### ISSUE TITLE
New users can't sign up for Slack

### ISSUE THREAD

**Issue by cb1kenobi** [tidev/organization-docs#16]
The old tislack.org site had the ability for new users to register. That page is no longer online, but can be viewed on the Internet Archive: https://web.archive.org/web/20201203064347/https://tislack.org/signup.

Today, we do not have a link on https://tidev.slack.com/ to register and we need one.

- [x] Create landing page site
- [x] Create Dokku app for site
- [x] Deploy site
- [x] Set up DNS for slack.tidev.io
- [x] Set up TLS
- [x] Update tislack.org redirect
- [x] Update links on tidev.io and titaniumsdk.com

**Comment by caspahouzer** [comment]
This is the link I used on tislack.org
https://join.slack.com/t/ti-slack/shared_invite/zt-ctkf9ew4-n0j5CCZ02fmJeHmcltxElw
It works longer than 30 days

**Comment by cb1kenobi** [comment]
I guess I don't get why we need to "invite" people. It should be as simple as go to tidev.slack.com and sign in/up. I don't think we want Slack to be an invite only community and I don't think WE should have a landing page that says to click the invite link.

Right now, if I try to sign in with a fresh email address, I get:

```
email@domain.com doesn’t have an account on this workspace.
```

I'm not a Slack admin, so maybe you can see if there's a way to disable the whole invite thing. There has to be a better way.

**Comment by caspahouzer** [comment]
Of course there shouldn't be a need to invite. We also can just use tidev.slack.com

**Comment by cb1kenobi** [comment]
Well, here's the site! https://github.com/tidev/tidev-slack.

Waiting on someone to create a DNS A record for slack.tidev.io that points to 12.208.119.236.

**Comment by caspahouzer** [comment]
Can this be closed?

**Comment by caspahouzer** [comment]
titaniumsdk.com : https://github.com/tidev/titanium_mobile/pull/13445

**Comment by caspahouzer** [comment]
https://tidev.io is also updated.

I now close this issue
