### ISSUE TITLE
tidev.io dns records

### ISSUE THREAD

**Issue by m1ga** [tidev/organization-docs#21]
Mentioned that a while ago in slack (and I thought it was fixed at some point :thinking: ):

https://www.nslookup.io/dns-records/tidev.io  -> works
https://www.nslookup.io/dns-records/www.tidev.io -> no entries

http://tidev.io/ doesn't forward to https. That should be default and the www should forward to non www too (or work)

**Comment by joshualambert** [comment]
I'll take this one.

**Comment by cb1kenobi** [comment]
Verified this is working. Thanks!
