### ISSUE TITLE
Committer Nomination: Ewan Harris

### ISSUE THREAD

**Issue by cb1kenobi** [tidev/organization-docs#24]
I nominate Ewan Harris for commit access to all TiDev repos. He's been a contributor to Titanium for over 7 years, one of the key maintainers of all Node packages, VSCode and Atom extensions, and engineer of many things. He's also very good at reviewing PRs.

His profile can be found here: https://github.com/ewanharris

Upon joining the TiDev committers, he can assist with getting various repos up-to-date, cleaning up the CI processes, and publishing stuff.

**Comment by joshualambert** [comment]
I vote yes in this.

**Comment by caspahouzer** [comment]
+1

**Comment by jasonkneen** [comment]
+1

**Comment by raybelisle** [comment]
+1

**Comment by cb1kenobi** [comment]
Voting has completed.

Yes: 5
No: 0
No vote: 1

Congratulation @ewanharris! Welcome to the TiDev committers!
