### ISSUE TITLE
Committer Nomination: Marc Bender

### ISSUE THREAD

**Issue by caspahouzer** [tidev/organization-docs#27]
I nominate Marc Bender for commit access to all TiDev repos. He's been a long time community member and contributor to Titanium. He's contributed numerous pull requests, modules, and support over the years.

His profile can be found here: https://github.com/mbender74

Upon joining the TiDev committers, he can assist with tackling the roadmap and improving modules.

**Comment by joshualambert** [comment]
I've interacted with his work and it's solid also. +1 for giving him module committer access.

**Comment by joshualambert** [comment]
@caspahouzer Note that he needs to get a CLA on file following the directions here before we can grant this though: https://github.com/tidev/organization-docs/blob/main/AUTHORIZED_CONTRIBUTORS.md

**Comment by cb1kenobi** [comment]
@caspahouzer you say he's contributed numerous pull requests and modules, but I can't find a single pull request or commit that he's ever submitted. As stated in https://github.com/tidev/organization-docs/blob/main/BECOMING_A_COMMITTER.md, only individuals with significant contributions shall be allowed commit access.

Commit access is a privilege and it has to be earned. I encourage Marc to find a project he's interested in and submit a couple new features and bug fixes.

If he donates modules to TiDev, then I can totally get behind giving him commit access to those donated repos, but I need to see more code contribution before granting him commit access to larger projects such as the SDK.

**Comment by caspahouzer** [comment]
Also we can be happy for every native Support in our situation. Yes, Hans makes a lot, but there is a need for small work or just reviewing the PR. I honestly can’t do that, because I have no native iOS  understanding

**Comment by cb1kenobi** [comment]
Anyone can contribute to any TiDev project, but it doesn't mean they NEED commit access. Remember, pull requests are supposed to be reviewed by someone else to make sure the change is sound, CLA is signed, tests are passing, and so on. People are welcome to submit a feature or improvement or review a PR, but that doesn't mean they get commit access.

If Marc has a lot of ideas, then I would love for him to start implementing those and then we can review them. After significant contribution, we can revisit this nomination.

**Comment by caspahouzer** [comment]
He is contributing and that’s okay
