### ISSUE TITLE
Setup website for the Jira dump.

### ISSUE THREAD

**Issue by joshualambert** [tidev/organization-docs#7]
- [x] Setup TiDev payment method on TiDev GoDaddy account. (@joshualambert will take this action item.)
- [x] Transfer TiSdk.com the domain to the TiDev GoDaddy account. (@cb1kenobi currently owns this one. he will move it.)
- [x] Setup static site generation of the Jira dump.
- [x] Setup server environment to hold the static site once it's built.
- [x] Point sub domain at new server environment
- [x] Test it!
- [x] Link to this site from TitaniumSDK.com
- [x] Distribute the Jira dump link on the TiDiscord.

**Comment by jasonkneen** [comment]
Why does it need to be transferred to a godaddy domain? It's fine on enom.

**Comment by joshualambert** [comment]
I have the TiDev payment method attached to GoDaddy now, have purchased the transfer, and it is scheduled to land in the TiDev GoDaddy account in February. moving on to getting the hosting setup now. @cb1kenobi

**Comment by joshualambert** [comment]
I got the VM hosting environment setup on this now and attached to tidev.smalltownhosting.com. This is on @cb1kenobi now to setup Dokku and Nginx to complete this ticket. Well on our way!!!

**Comment by cb1kenobi** [comment]
This is done and available on https://jira-archive.titaniumsdk.com.
