### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by cb1kenobi** [tidev/organization-docs#8]
Here's what needs to be in these guidelines:

1.) Requirement that all code be licensed under Apache 2, with a CLA requirement as described on this ticket #11.
2.) What official repos to use (Github) for TIDev contributions.
3.) How to file bugs for TiDev projects. (We need these tests, attachments, etc.)
4.) How to submit a patch to TiDev projects. (What must be included in a PR for it to be merged.)
5.) How to suggest edits to the website. (No idea on this but someone needs to think it through.)

Apache License:
https://www.apache.org/licenses/LICENSE-2.0

Apache Contributor Guidelines which is a helpful guide in figuring out our version of these documents: https://infra.apache.org/contributors.html

**_I would consider this issue resolved by a MD file CONTRIBUTOR_GUIDELINES checked into organization-docs that hits the 5 points above. To resolve, open a PR with an MD file that covers those points for review._**

**Comment by joshualambert** [comment]
I like this breakdown on this one over at Apache. Seems like we could remix this into a MD file and drop it into the organization-docs as well: https://infra.apache.org/contributors.html

**Comment by cb1kenobi** [comment]
The contributor guidelines have been published here: https://titaniumsdk.com/contribute.html. I suspect this will be duplicated over to tidev.io at a later date.
